default: all

all: iralib fsrc py

iralib:
	@cd IRA/src; make all; cd -
fsrc:
	@cd src; make; cd -

py:
	@cd interf; python3 setup.py build_ext --inplace; cd -

clean-fsrc:
	@cd src; make clean; cd -

clean-py:
	@cd interf; rm -rf build/ py_itm.*.so __pycache__ py_itm.c; cd -

clean: clean-fsrc clean-py


help:
	@echo 'Usage: make [target]'
	@echo ''
	@echo ' Possible targets:'
	@echo ''
	@echo '     all      -> compile all needed files'
	@echo '     fsrc     -> compile the src directory'
	@echo '     py       -> compile cython module in interf directory'
	@echo '     iralib   -> compile the IRA library'
	@echo ''
	@echo '     clean      -> remove all files generated by make'
	@echo '     clean-fsrc -> clean the src diretory'
	@echo '     clean-py   -> clean the interf directory'
	@echo ''
	@echo ' Quitting.'
